<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fm_elfinder.configurator.default' shared service.

include_once $this->targetDirs[3].'\\vendor\\helios-ag\\fm-elfinder-bundle\\src\\Model\\ElFinderConfigurationProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\helios-ag\\fm-elfinder-bundle\\src\\Configuration\\ElFinderConfigurationReader.php';

return $this->services['fm_elfinder.configurator.default'] = new \FM\ElfinderBundle\Configuration\ElFinderConfigurationReader($this->parameters['fm_elfinder'], ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'}, $this);
