<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.form.type' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Form\\AbstractType.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\ckeditor-bundle\\src\\Form\\Type\\CKEditorType.php';

return $this->services['fos_ck_editor.form.type'] = new \FOS\CKEditorBundle\Form\Type\CKEditorType(${($_ = isset($this->services['fos_ck_editor.configuration']) ? $this->services['fos_ck_editor.configuration'] : $this->load('getFosCkEditor_ConfigurationService.php')) && false ?: '_'});
