<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_paginator.subscriber.filtration' shared service.

include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-components\\src\\Knp\\Component\\Pager\\Event\\Subscriber\\Filtration\\FiltrationSubscriber.php';

return $this->services['knp_paginator.subscriber.filtration'] = new \Knp\Component\Pager\Event\Subscriber\Filtration\FiltrationSubscriber();
