<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.installer' shared service.

include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\ckeditor-bundle\\src\\Installer\\CKEditorInstaller.php';

return $this->services['fos_ck_editor.installer'] = new \FOS\CKEditorBundle\Installer\CKEditorInstaller();
