<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_paginator.subscriber.paginate' shared service.

include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-components\\src\\Knp\\Component\\Pager\\Event\\Subscriber\\Paginate\\PaginationSubscriber.php';

return $this->services['knp_paginator.subscriber.paginate'] = new \Knp\Component\Pager\Event\Subscriber\Paginate\PaginationSubscriber();
