<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQsdrxpy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQsdrxpy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQsdrxpy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQsdrxpy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQsdrxpy\appDevDebugProjectContainer([
    'container.build_hash' => 'Qsdrxpy',
    'container.build_id' => '77ff0888',
    'container.build_time' => 1591433349,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQsdrxpy');
