<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZb3nego\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZb3nego/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZb3nego.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZb3nego\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZb3nego\appDevDebugProjectContainer([
    'container.build_hash' => 'Zb3nego',
    'container.build_id' => 'bef01d15',
    'container.build_time' => 1591553040,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZb3nego');
